server.port: 5000
#spring.datasource.url: jdbc:mysql://localhost:3306/viswa?serverTimezone=Asia/Singapore&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.url: jdbc:postgresql://localhost:5432/poc
spring.datasource.username: myuser
spring.datasource.password: mypwd
spring.datasource.driver-class-name: org.postgresql.Driver
spring.jpa.show-sql: true
#spring.jpa.dialect: org.hibernate.dialect.MySQL8Dialect
#spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
#spring.jpa.database-platform: org.hibernate.dialect.MySQL8Dialect
#spring.jpa.dialect: org.postgresql.Driver
#spring.jpa.properties.hibernate.dialect: org.postgresql.Driver
#spring.jpa.database-platform: org.postgresql.Driver
spring.jpa.properties.hibernate.id.new_generator_mappings: false

spring:
  datasource:
    schema: classpath:droptables.sql, classpath:schema-postgres.sql
#    data: classpath:data-static.sql
    initialization-mode: always
    auto-commit: true
    jpa:
      show-sql: true
      format-sql: true
      use-sql-comments: true
  #  test:
  #    database:
  #      replace: NONE  # run mySQL (instead of the default H2 embedded database). or @AutoConfigureTestDatabase(replace=Replace.NONE) or @EnableAutoConfiguration(exclude=AutoConfigureTestDatabase.class)
  jpa:
    generate-ddl: true
    hibernate:
      #      ddl-auto: validate, update, create, create-drop, none
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  cache:
    type: none
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false



logging:
  file.clean-history-on-start: true
  pattern.console: "%M - %msg%n"
  pattern.file: "%msg%n"

